refactor: move selected edit suggestion to other suggestions
end-of-text/endoftext pull request #130
Opened 2024-03-04 12:08 UTC by Sparkier

towards EOT-54

2024-03-04 14:28 UTC, cabreraalex commented
This is AWESOME!!!!

2024-03-04 16:44 UTC, cabreraalex requested changes

2024-03-04 16:44 UTC, cabreraalex commented on src/lib/components/prompt/PromptEditor.svelte
Can we still show what is being highlighted as you drag? It's a bit confusing that it doesn't show until you lift.

2024-03-04 16:44 UTC, cabreraalex commented on src/lib/components/prompt/PromptEditor.svelte
The drag also isn't accurate, it will go a bit too far or too short

2024-03-04 16:44 UTC, cabreraalex commented on src/lib/components/prompt/PromptEditor.svelte
IDK if this is possible but you should also be able to edit the text that is underlined. Right now when you click on underlined text it just filters the selection. It should still act like a normal editor that you can change.

2024-03-04 16:44 UTC, cabreraalex commented on src/lib/components/prompt/PromptEditor.svelte
When I apply a single line edit and then manually edit the underlines come back but they are "broken"

2024-03-04 17:11 UTC, Sparkier commented on src/lib/components/prompt/PromptEditor.svelte
You can but since we're watching for the click it's tricky. You have to begin the selection slightly outside. Don't know how else to do that if we want people to be able to click on the underlined part.

2024-03-04 19:30 UTC, Sparkier commented
> It's now not showing the diff when you apply an editor

so many edge cases

2024-03-05 04:12 UTC, cabreraalex commented
Yeah RIP now the red underline doesn't go away when you start editing it.

2024-03-06 04:27 UTC, cabreraalex approved these changes

2024-03-06 04:27 UTC, merged