feat: markdown editor
end-of-text/endoftext pull request #131
Opened 2024-03-05 04:50 UTC by cabreraalex

2024-03-05 08:30 UTC, Sparkier requested changes

2024-03-05 08:30 UTC, Sparkier commented on src/lib/components/prompt/RewriteSuggestion.svelte
> +		<h4>Rewrite the selected text</h4>
This has been updated.

2024-03-05 08:30 UTC, Sparkier commented on src/lib/components/prompt/RewriteSuggestion.svelte
> +<script lang="ts">
maybe separate PR?

2024-03-06 04:30 UTC, cabreraalex commented on src/lib/server/editors/MarkdownEditor.ts
> +const applyPrompt = await fetchPrompt('iXgXi2Wk', '788');
shared!

2024-03-06 04:30 UTC, cabreraalex commented on src/lib/server/editors/MarkdownEditor.ts
> +		}
good catch, from copying over.

2024-03-06 04:31 UTC, cabreraalex commented on src/lib/components/prompt/RewriteSuggestion.svelte
> +<script lang="ts">
yeah sorry included by accident

2024-03-06 08:58 UTC, Sparkier approved these changes
lgtm generally but this is not in the editors list yet, right? Also not in hypertune.

2024-03-19 23:29 UTC, merged